//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.34209
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace KommIT.ebyggesoknad.Models.Altinn {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Dispensasjonstype", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class DispensasjonstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Eiendom", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class EiendomType {
        
        private EnkelAdresseType adresseField;
        
        private MatrikkelnummerType eiendomsidentifikasjonField;
        
        private string bygningsnummerrField;
        
        private string bolignummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnkelAdresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrikkelnummerType eiendomsidentifikasjon {
            get {
                return this.eiendomsidentifikasjonField;
            }
            set {
                this.eiendomsidentifikasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bygningsnummerr {
            get {
                return this.bygningsnummerrField;
            }
            set {
                this.bygningsnummerrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bolignummer {
            get {
                return this.bolignummerField;
            }
            set {
                this.bolignummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("EnkelAdresse", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class EnkelAdresseType {
        
        private string adresselinje1Field;
        
        private string adresselinje2Field;
        
        private string adresselinje3Field;
        
        private string postnrField;
        
        private string poststedField;
        
        private string landkodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje1 {
            get {
                return this.adresselinje1Field;
            }
            set {
                this.adresselinje1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje2 {
            get {
                return this.adresselinje2Field;
            }
            set {
                this.adresselinje2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje3 {
            get {
                return this.adresselinje3Field;
            }
            set {
                this.adresselinje3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postnr {
            get {
                return this.postnrField;
            }
            set {
                this.postnrField = value;
            }
        }
        
        /// <remarks/>
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string landkode {
            get {
                return this.landkodeField;
            }
            set {
                this.landkodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Matrikkelnummer", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class MatrikkelnummerType {
        
        private string kommunenummerField;
        
        private string gaardsnummerField;
        
        private string bruksnummerField;
        
        private string festenummerField;
        
        private string seksjonsnummerField;
        
        /// <remarks/>
        public string kommunenummer {
            get {
                return this.kommunenummerField;
            }
            set {
                this.kommunenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string gaardsnummer {
            get {
                return this.gaardsnummerField;
            }
            set {
                this.gaardsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string bruksnummer {
            get {
                return this.bruksnummerField;
            }
            set {
                this.bruksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string festenummer {
            get {
                return this.festenummerField;
            }
            set {
                this.festenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string seksjonsnummer {
            get {
                return this.seksjonsnummerField;
            }
            set {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("NaboGjenboer", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class NaboGjenboerType : PartType {
        
        private EiendomType gjelderNaboeiendomField;
        
        private System.Nullable<System.DateTime> epostSendtField;
        
        private bool epostSendtFieldSpecified;
        
        private bool harPersonligMottattVarselField;
        
        private System.Nullable<System.DateTime> personligMottattVarselField;
        
        private bool personligMottattVarselFieldSpecified;
        
        private bool harPersonligSamtykkeTilTiltaketField;
        
        private System.Nullable<System.DateTime> personligSamtykkeTilTiltaketField;
        
        private bool personligSamtykkeTilTiltaketFieldSpecified;
        
        /// <remarks/>
        public EiendomType gjelderNaboeiendom {
            get {
                return this.gjelderNaboeiendomField;
            }
            set {
                this.gjelderNaboeiendomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> epostSendt {
            get {
                return this.epostSendtField;
            }
            set {
                this.epostSendtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool epostSendtSpecified {
            get {
                return this.epostSendtFieldSpecified;
            }
            set {
                this.epostSendtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool harPersonligMottattVarsel {
            get {
                return this.harPersonligMottattVarselField;
            }
            set {
                this.harPersonligMottattVarselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> PersonligMottattVarsel {
            get {
                return this.personligMottattVarselField;
            }
            set {
                this.personligMottattVarselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonligMottattVarselSpecified {
            get {
                return this.personligMottattVarselFieldSpecified;
            }
            set {
                this.personligMottattVarselFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool harPersonligSamtykkeTilTiltaket {
            get {
                return this.harPersonligSamtykkeTilTiltaketField;
            }
            set {
                this.harPersonligSamtykkeTilTiltaketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> PersonligSamtykkeTilTiltaket {
            get {
                return this.personligSamtykkeTilTiltaketField;
            }
            set {
                this.personligSamtykkeTilTiltaketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonligSamtykkeTilTiltaketSpecified {
            get {
                return this.personligSamtykkeTilTiltaketFieldSpecified;
            }
            set {
                this.personligSamtykkeTilTiltaketFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TiltakshaverType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NaboGjenboerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Part", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class PartType {
        
        private PartstypeType partstypeField;
        
        private string foedselsnummerField;
        
        private string organisasjonsnummerField;
        
        private string navnField;
        
        private EnkelAdresseType adresseField;
        
        private string telefonnummerField;
        
        private string mobilnummerField;
        
        private string epostField;
        
        /// <remarks/>
        public PartstypeType partstype {
            get {
                return this.partstypeField;
            }
            set {
                this.partstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string foedselsnummer {
            get {
                return this.foedselsnummerField;
            }
            set {
                this.foedselsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string organisasjonsnummer {
            get {
                return this.organisasjonsnummerField;
            }
            set {
                this.organisasjonsnummerField = value;
            }
        }
        
        /// <remarks/>
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnkelAdresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobilnummer {
            get {
                return this.mobilnummerField;
            }
            set {
                this.mobilnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string epost {
            get {
                return this.epostField;
            }
            set {
                this.epostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Partstype", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class PartstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Nabovarsel", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class NabovarselType {
        
        private EiendomType[] eiendomByggestedField;
        
        private TiltakstypeType[] tiltakstyperField;
        
        private DispensasjonstypeType[] dispensasjonstyperField;
        
        private PlanType gjeldendePlanField;
        
        private string beskrivelseAvTiltaketField;
        
        private TiltakshaverType tiltakshaverField;
        
        private PartType[] eiereField;
        
        private VedleggType[] vedleggField;
        
        private NaboGjenboerType[] naboerField;
        
        private string soeknadensHjemmesideField;
        
        private string dataFormatProviderField;
        
        private string dataFormatIdField;
        
        private string dataFormatVersionField;
        
        public NabovarselType() {
            this.dataFormatProviderField = "KXML";
            this.dataFormatIdField = "4782";
            this.dataFormatVersionField = "33264";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("eiendom", IsNullable=false)]
        public EiendomType[] eiendomByggested {
            get {
                return this.eiendomByggestedField;
            }
            set {
                this.eiendomByggestedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("tiltakstype", IsNullable=false)]
        public TiltakstypeType[] tiltakstyper {
            get {
                return this.tiltakstyperField;
            }
            set {
                this.tiltakstyperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dispensasjonstype", IsNullable=false)]
        public DispensasjonstypeType[] dispensasjonstyper {
            get {
                return this.dispensasjonstyperField;
            }
            set {
                this.dispensasjonstyperField = value;
            }
        }
        
        /// <remarks/>
        public PlanType gjeldendePlan {
            get {
                return this.gjeldendePlanField;
            }
            set {
                this.gjeldendePlanField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelseAvTiltaket {
            get {
                return this.beskrivelseAvTiltaketField;
            }
            set {
                this.beskrivelseAvTiltaketField = value;
            }
        }
        
        /// <remarks/>
        public TiltakshaverType tiltakshaver {
            get {
                return this.tiltakshaverField;
            }
            set {
                this.tiltakshaverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("part", IsNullable=false)]
        public PartType[] eiere {
            get {
                return this.eiereField;
            }
            set {
                this.eiereField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vedlegg", IsNullable=false)]
        public VedleggType[] vedlegg {
            get {
                return this.vedleggField;
            }
            set {
                this.vedleggField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("nabogjenboer", IsNullable=false)]
        public NaboGjenboerType[] naboer {
            get {
                return this.naboerField;
            }
            set {
                this.naboerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string soeknadensHjemmeside {
            get {
                return this.soeknadensHjemmesideField;
            }
            set {
                this.soeknadensHjemmesideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatProvider {
            get {
                return this.dataFormatProviderField;
            }
            set {
                this.dataFormatProviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatId {
            get {
                return this.dataFormatIdField;
            }
            set {
                this.dataFormatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatVersion {
            get {
                return this.dataFormatVersionField;
            }
            set {
                this.dataFormatVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Tiltakstype", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class TiltakstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Plan", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class PlanType {
        
        private PlantypeType plantypeField;
        
        private string navnField;
        
        /// <remarks/>
        public PlantypeType plantype {
            get {
                return this.plantypeField;
            }
            set {
                this.plantypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Plantype", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class PlantypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Tiltakshaver", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class TiltakshaverType : PartType {
        
        private bool soeknad_personlig_ansvarsrettField;
        
        /// <remarks/>
        public bool Soeknad_personlig_ansvarsrett {
            get {
                return this.soeknad_personlig_ansvarsrettField;
            }
            set {
                this.soeknad_personlig_ansvarsrettField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Vedlegg", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class VedleggType {
        
        private bool elektroniskVedleggField;
        
        private string filnavnField;
        
        private string kommentarField;
        
        private System.Nullable<bool> postbasertVedleggField;
        
        private bool postbasertVedleggFieldSpecified;
        
        private VedleggstypeType vedleggstypeField;
        
        /// <remarks/>
        public bool elektroniskVedlegg {
            get {
                return this.elektroniskVedleggField;
            }
            set {
                this.elektroniskVedleggField = value;
            }
        }
        
        /// <remarks/>
        public string filnavn {
            get {
                return this.filnavnField;
            }
            set {
                this.filnavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kommentar {
            get {
                return this.kommentarField;
            }
            set {
                this.kommentarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> postbasertVedlegg {
            get {
                return this.postbasertVedleggField;
            }
            set {
                this.postbasertVedleggField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postbasertVedleggSpecified {
            get {
                return this.postbasertVedleggFieldSpecified;
            }
            set {
                this.postbasertVedleggFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public VedleggstypeType vedleggstype {
            get {
                return this.vedleggstypeField;
            }
            set {
                this.vedleggstypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Vedleggstype", Namespace="http://skjema.kxml.no/dibk/nabovarsel/0.9", IsNullable=false)]
    public partial class VedleggstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
}
